; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Dark Night Beta"
#define MyAppVersion "1.0"
#define MyAppPublisher "Legends"
#define MyAppURL "http://www.github.com/pogirae/CS191-ACT-Repository"
#define MyAppExeName "DarkNight.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{9D71A2B8-BE68-4936-8BE2-8DEBDD0D9490}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={pf}\{#MyAppName}
DefaultGroupName={#MyAppName}
LicenseFile=C:\Users\user\Google Drive\CS 192\Source Files\LICENSE.txt
InfoBeforeFile=C:\Users\user\Google Drive\CS 192\Source Files\start.txt
OutputBaseFilename=setup_darknight_v1beta
Compression=lzma
SolidCompression=yes
VersionInfoVersion=1.0
VersionInfoCompany=Legends

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{group}\{cm:ProgramOnTheWeb,{#MyAppName}}"; Filename: "{#MyAppURL}"
Name: "{group}\{cm:UninstallProgram,{#MyAppName}}"; Filename: "{uninstallexe}"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Flags: nowait postinstall skipifsilent; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; MinVersion: 0,6.1

[Dirs]
Name: "{app}\Include\Include"
Name: "{app}\soundfiles\soundfiles"

[Files]
Source: "dist\DarkNight\DarkNight.exe"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\bz2.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\DarkNight.exe.manifest"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\Microsoft.VC90.CRT.manifest"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\msvcm90.dll"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\msvcp90.dll"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\msvcr90.dll"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\pyexpat.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\python27.dll"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\pywintypes27.dll"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\select.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\unicodedata.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\win32pipe.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\_ctypes.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\_hashlib.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\_socket.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\_ssl.pyd"; DestDir: "{app}\"; Flags: ignoreversion
Source: "dist\DarkNight\Include\pyconfig.h"; DestDir: "{app}\Include\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\battlebg.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\battleinst.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\battlemode.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\battlemode.wav"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\castleentry.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\cheering.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\cheering.wav"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\desktop.ini"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog1_1.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog1_2.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog1_3.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog1_4.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog1_5.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog1_6.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_1.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_10.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_11.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_12.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_13.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_14.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_15.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_16.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_17.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_18.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_19.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_2.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_20.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_21.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_22.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_23.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_24.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_25.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_26.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_27.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_28.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_3.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_4.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_5.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_6.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_7.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_8.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog2_9.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_1.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_10.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_11.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_12.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_13.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_14.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_15.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_16.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_17.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_18.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_19.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_2.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_20.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_3.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_4.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_5.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_6.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_7.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_8.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\dialog3_9.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\disabledialog.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\enabledialog.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\footstep.wav"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\hit.wav"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\horn.wav"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\instructions.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\king_dead.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\left.mp3"; DestDir: "{app}\soundfiles"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\lose.wav"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\mainmenu.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\panic_scream.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\pressany.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\pressenter.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\right.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\shiphorn.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\stab_king.wav"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\start1.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\sword.wav"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\thud_king.wav"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\trumpet.wav"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\welcome.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
Source: "dist\DarkNight\soundfiles\win.mp3"; DestDir: "{app}\soundfiles\"; Flags: ignoreversion
